---
- name: conveying files via template
  template:
    src: "{{item.src_file}}"
    dest: "{{item.dest_file}}"
  loop:
    - {
        src_file: "nginx.conf.j2",
        dest_file: "/etc/nginx/nginx.conf",
      }
    - {
        src_file: "gunicorn.socket.j2",
        dest_file: "/etc/systemd/system/gunicorn.socket",
      }  
    - {
        src_file: "gunicorn.service.j2",
        dest_file: "/etc/systemd/system/gunicorn.service",
      }    
  notify:
    - reload_nginx
    # - reload_postgresql
    - gunicorn_service

- name: remove simlink default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - reload_nginx   
